spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grupo-18-db
    username: root
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
